### ISSUE TITLE
Cohere Command R Plus

### ISSUE THREAD

**Issue by Khaledhesham** [OpenGVLab/EfficientQAT#10]
Is there a way I could use this to quantize cohere command r plus model ?

**Comment by ChenMnZ** [comment]
Hi, EfficientQAT can be used to quantized all LLMs.

The only things you should do to support other models is modified https://github.com/OpenGVLab/EfficientQAT/blob/346d98a9eff3fe1c5283a3b27831c20f153e516c/quantize/block_ap.py#L46-L50 and https://github.com/OpenGVLab/EfficientQAT/blob/346d98a9eff3fe1c5283a3b27831c20f153e516c/quantize/block_ap.py#L46-L50
to adapt do different architectures.
