### ISSUE TITLE
Evaluation pipeline points to missing files

### ISSUE THREAD

**Issue by snps-tonatiuh** [OpenGVLab/EfficientQAT#11]
I am following the README to evaluate a model with
```bash 
CUDA_VISIBLE_DEVICES=0 python main_block_ap.py \
--resume_quant ./output/pre_quantized_models/Llama-2-7b-EfficientQAT-w2g64 \
--net Llama-2 \
--wbits 2 \
--group_size 64 \
--output_dir ./output/inference_results/ \
--eval_ppl \
--eval_tasks  piqa,arc_easy,arc_challenge,hellaswag,winogrande
```

But I get an error due to hard-coded file locations:
```
FileNotFoundError: Unable to find '/cpfs01/user/chenmengzhao/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/json-train-00000-of-00002.arrow'
```

**Comment by ChenMnZ** [comment]
You can delete the following code to  solve this problem.
https://github.com/OpenGVLab/EfficientQAT/blob/346d98a9eff3fe1c5283a3b27831c20f153e516c/datautils_block.py#L47-L60 
I have wrapped such code with `try & except`, it is curious to report error.

**Comment by snps-tonatiuh** [comment]
I don't understand why the `try, except` block did not work as expected, but thanks anyways.
