### ISSUE TITLE
Reproduce Llama2-7b

### ISSUE THREAD

**Issue by laomao0** [OpenGVLab/EfficientQAT#13]
I reproduce the results of Block-ap PPL, wikitext2 7.76 c4 9.50 [Llama2-7b-w2g64], logs below.
I use the auther released weight [1] to test, the result is  7.65, 9.36. Are there something to notice for training the model,
or just the randomness to cause the PPL shift?

[1]https://huggingface.co/ChenMnZ/Llama-2-7b-BlockAP-w2g64/tree/main

**Comment by ChenMnZ** [comment]
I found that all released models are trained for 2 epochs, except that w2g64 llama-2-7b is trained for 3 epochs.

So, the 0.1 ppl difference maybe caused by different training epoch.

Additionally, such negligible ppl difference in 2-bit can be compensated in the following e2e-qp process.

**Comment by laomao0** [comment]
> I found that all released models are trained for 2 epochs, except that w2g64 llama-2-7b is trained for 3 epochs.
> 
> So, the 0.1 ppl difference maybe caused by different training epoch.
> 
> Additionally, such negligible ppl difference in 2-bit can be compensated in the following e2e-qp process.

Thanks for your quick replay. 

By the way, in Table 8, the training time of Llama-2-7b [block-ap] is 3.3h, what is the training setting for this? I see the log in my reproduced w2g64-llama2-7b epoch 2, need about 7h to quant 32 layers?

Thanks.

**Comment by ChenMnZ** [comment]
@laomao0 
The lower training speed is resulted by pytorch dataloader.

I try to rewrite the data processing code through pytorch dataloader to make the code more clear.

However, such operation lead memory bottleneck and lower GPU use ratio (can be seen through nvidia-smi).

I'm still trying to fix this.

**Comment by ChenMnZ** [comment]
@laomao0 
I have fixed the bottleneck of data processing. You can clone the latest code for the faster training speed.
