### ISSUE TITLE
Question about calib datasets.

### ISSUE THREAD

**Issue by mxjmtxrm** [OpenGVLab/EfficientQAT#16]
Hi, I want to do QAT for a fine-tuned model. I don't know what to choose as the calib dataset. Do you have any suggestions? And does it achieve the same results as the pre-trained model mentioned in the paper?

**Comment by ChenMnZ** [comment]
Yeah, dataset selection is crucial to the fine-tuned model, and e2e-qp can also significantly boost the performance of quantized fine-tuned model with appropriate dataset. 
Two suggestion for the dataset:
- use a small subset from the original fine-tuned dataset (if it is accessible)
- use the deita-10k dataset (which we used for llama-3-8b-instruct, refer https://github.com/OpenGVLab/EfficientQAT/blob/main/examples/e2e_qp/Llama-3-8b-instruct/w2g64-deita.sh for details) and make sure seting the consistent chat template with the fine-tuned process by `--conv_temp`.

**Comment by mxjmtxrm** [comment]
What about the block_ap stage?

**Comment by ChenMnZ** [comment]
Block-ap is less sensitive to datasets. 

Therefore, redpajama, c4, or the original fine-tuned dataset all is ok.
