### ISSUE TITLE
Reproduce Llama3 8B Instruct results

### ISSUE THREAD

**Issue by gdsaikrishna** [OpenGVLab/EfficientQAT#21]
Hi, I am trying to reproduce the Llama3 8B Instruct Results. Whats the config you ran for E2E finetuning of Llama3 8B instruct Model ?

1. Which dataset are we using for E2E fine tuning step of Llama3 8B Instruct Model ? 
2. Does the section "**4.2 EfficientQAT for Instruction Tuning**" mentioned in the paper applicable for this model?
3. Whats the conv template used for Llama 3 8B instruct model (Llama3 or Llama2)? As I found only Llama2 Template in deita dataset preprocessing.

**Comment by ChenMnZ** [comment]
Thanks for your interesting. The answer for your question is:
1.  We use deita-10k for the e2e fine tuning of llama-3-8B-Instruct. You can refer `examples/e2e_qp/Llama-3-8b-instruct` for the detailed training scripts.
2. No. Sec 4.2 trains base model on Alpaca Dataset, just for easy comparisons with previous methods.
3. Thanks for your reminder.  I do a wrong thing.  I train Llama-3-8B-Instruct with Llama2 chatting template previously.  It is better to train the instruction-tuned models with their original chatting template.

**Comment by gdsaikrishna** [comment]
Thanks for your reply @ChenMnZ

**Comment by RYY177** [comment]
> Thanks for your interesting. The answer for your question is:
> 
> 1. We use deita-10k for the e2e fine tuning of llama-3-8B-Instruct. You can refer `examples/e2e_qp/Llama-3-8b-instruct` for the detailed training scripts.
> 2. No. Sec 4.2 trains base model on Alpaca Dataset, just for easy comparisons with previous methods.
> 3. Thanks for your reminder.  I do a wrong thing.  I train Llama-3-8B-Instruct with Llama2 chatting template previously.  It is better to train the instruction-tuned models with their original chatting template.

Hello, I’m also working on reproducing the fine-tuning of llama3-8b-instruction recently.
I’d like to ask whether I should directly use end-to-end fine-tuning, or first perform Block-AP and then do end-to-end fine-tuning.

**Comment by ChenMnZ** [comment]
@RYY177 
You should first perform Block-AP and then do end-to-end fine-tuning.

**Comment by RYY177** [comment]
> [@RYY177](https://github.com/RYY177) You should first perform Block-AP and then do end-to-end fine-tuning.

Thanks for your reply. 
During the training of Llama-3-8B, I followed the same approach as with Llama-2-7B by using the Alpaca dataset for block-AP and the Deita-10K dataset for end-to-end training. However, I observed that the results kept deteriorating in both stages. Could you please share the dataset and settings used for block-AP in Llama-3-8B?

**Comment by HXuan-Wang** [comment]
@RYY177 请教一下，你有尝试到合适的Llama-3-8B的训练配置吗，我发现block-ap阶段没有llama3的训练脚本，采用llama2的训练脚本跟论文里的结果有明显的差异
