### ISSUE TITLE
question about real quant

### ISSUE THREAD

**Issue by mxjmtxrm** [OpenGVLab/EfficientQAT#4]
Hi, I noticed that e2e_qp only accepts real quantized model, right? How to conduct the second phase on the fake quantized model?

**Comment by ChenMnZ** [comment]
You can leverage `main_block_ap.py` to convert fake quantized model into real quantized ones.
An example to convert w2g64 is as follow:
```
CUDA_VISIBLE_DEVICES=0 python main_block_ap.py \
--model path/to/fake_quant_model  \
--output_dir ./output/block_ap_log/temp \
--net Llama-2 \
--wbits 2 \
--group_size 64 \
--epoch 0 \
--real_quant \
--eval_ppl \
--save_quant_dir path/to/real_quant_model  \
```

**Comment by mxjmtxrm** [comment]
I want a fake quantized model after stage 2 rather than a GPTQ model. Is there any wat to do this?

**Comment by ChenMnZ** [comment]
Try this function:
https://github.com/OpenGVLab/EfficientQAT/blob/ed875349dba09b5d6b98e6a5de744a46972b8407/quantize/int_linear_real.py#L79

**Comment by mxjmtxrm** [comment]
Call this function after `q_linear = QuantLinear(wbits, group_size, module.in_features,module.out_features,not module.bias is None)` right？like `q_linear. use_fake_quantization()`

**Comment by mxjmtxrm** [comment]
@ChenMnZ Hi, could you please tell me how to use the `use_fake_quantization` function?
