### ISSUE TITLE
Data arrangement

### ISSUE THREAD

**Issue by yancaoweidaode** [OpenGVLab/EfficientQAT#7]
I see the model from https://hf-mirror.com/ChenMnZ/Llama-3-8b-instruct-EfficientQAT-w4g128/tree/main. But, I have a question, How can I de-quantize this safetensors model from int4 128block to f16 or f32, and store the data sequentially after de-quantization?

**Comment by ChenMnZ** [comment]
You can refer https://github.com/OpenGVLab/EfficientQAT/issues/4#issuecomment-2264427266 to achieve this goal.

**Comment by yancaoweidaode** [comment]
I know the dequantize formula is W = (W_int-Z) * S, but i don't konw the data arrangement in the model file.

**Comment by yancaoweidaode** [comment]
> You can refer [#4 (comment)](https://github.com/OpenGVLab/EfficientQAT/issues/4#issuecomment-2264427266) to achieve this goal.

what is the mean of fake quantization. it is fp16 or fp32?

**Comment by ChenMnZ** [comment]
Fake quantization indicates fp16 in our code. Anyway, you can also change it to fp32.

Additionally, what is the meaning of data arrangement?
